# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "efa2391e3ab7ea411b8e74566ce610b3"
name = "webhook-app"
handle = "webhook-app-36"
application_url = "https://2dc6-103-203-94-109.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "manupulation-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,unauthenticated_read_checkouts,unauthenticated_read_content,unauthenticated_read_customer_tags,unauthenticated_read_customers,unauthenticated_read_product_listings,unauthenticated_read_product_tags,unauthenticated_write_checkouts,unauthenticated_write_customers,write_customers,write_products"

[auth]
redirect_urls = [
  "https://2dc6-103-203-94-109.ngrok-free.app/auth/callback",
  "https://2dc6-103-203-94-109.ngrok-free.app/auth/shopify/callback",
  "https://2dc6-103-203-94-109.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
